"""add language to posts

Revision ID: 04935ce8fb80
Revises: 63cd00a22324
Create Date: 2018-03-24 02:31:46.199259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04935ce8fb80'
down_revision = '63cd00a22324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
